{{- if and .Values.notifications.enabled (not .Values.notifications.smtp.existingSecret) (or .Values.notifications.smtp.username .Values.notifications.smtp.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-defect-bot.smtpSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-defect-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtp-username: {{ .Values.notifications.smtp.username | quote }}
  smtp-password: {{ .Values.notifications.smtp.password | quote }}
{{- end }}
